services:
  auth_service_app:
    container_name: auth_service_app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uvicorn --factory presentation.api.auth_service.v1.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${AUTH_SERVICE_API_PORT}:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend
  weather_service_app:
    container_name: weather_service_app
    build:
      context: ..
      dockerfile: Dockerfile
    command: "uv run uvicorn --factory presentation.api.main:create_app --reload --host 0.0.0.0 --port 8000"
    ports:
      - '${WEATHER_SERVICE_API_PORT}:8000'
    volumes:
      - ../app/:/app
    env_file:
      - ../.env
    networks:
      - backend

networks:
  backend:
    driver: bridge
