[project]
name = "fastapi-ddd-boilerplate"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12"
dependencies = [
    "fastapi>=0.115.6",
    "pre-commit>=4.0.1",
    "punq>=0.7.0",
    "pydantic-settings>=2.7.1",
    "uvicorn>=0.34.0",
]
